include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = tests
tests_CPPFLAGS = -I../sources -I../SenTestingKit -fblocks
tests_OBJC_FILES = $(wildcard *.m)
tests_SUBPROJECTS = ../sources ../SenTestingKit

include $(GNUSTEP_MAKEFILES)/tool.make
