include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = common
common_CPPFLAGS = -fobjc-arc -fblocks
common_OBJC_FILES = CWSCore.m CWSCoreState.m CWSDirection.m CWSExecutionVector.m

include $(GNUSTEP_MAKEFILES)/subproject.make

