include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = yafacwesConsole
#yafacwesConsole_OBJC_PRECOMPILED_HEADERS = PrefixHeader.pch
yafacwesConsole_CPPFLAGS = -fobjc-arc -fblocks -I ../../sources
yafacwesConsole_OBJC_FILES = $(wildcard *.m)
yafacwesConsole_SUBPROJECTS = ../../sources

include $(GNUSTEP_MAKEFILES)/tool.make
